import time

class DeliveryInterface:
    """
    Designs a minimal, low-friction notification system for command delivery.

    This class simulates a desktop popup or mobile alert to ensure that the
    Command is presented visually separate from standard information.
    """

    def __init__(self, mode='desktop'):
        """
        Initializes the DeliveryInterface.

        Args:
            mode (str): The notification mode ('desktop', 'mobile', etc.).
        """
        self.mode = mode

    def deliver_command(self, command):
        """
        Displays the command in a simulated notification format.

        Args:
            command (str): The command string generated by the CommandGenerationEngine.
        """
        if self.mode == 'desktop':
            self._show_desktop_notification(command)
        else:
            print(f"DELIVERY [{self.mode.upper()}]: {command}")

    def _show_desktop_notification(self, command):
        """
        Simulates a desktop notification.
        """
        border = "!" * (len(command) + 4)
        print("\n" + border)
        print(f"! {command} !")
        print(border + "\n")

# Example Usage:
if __name__ == '__main__':
    # Simulating a command to be delivered
    generated_command = "PRIORITIZED DIRECTIVE: Your primary focus must be 'Draft investor update'. Defer all other tasks until this is complete."

    interface = DeliveryInterface(mode='desktop')

    print("--- Delivery Interface Simulation ---")
    print("A new command has been generated and will be delivered now.")
    time.sleep(1)
    interface.deliver_command(generated_command)
