"""
This module contains the CommandGenerationEngine using an LLM.
"""
from my_son.agent.llm import LLMClient

class CommandGenerationEngine:
    """
    Generates a command based on a high-value activity using an LLM.
    """

    def __init__(self):
        self.llm = LLMClient()

    def generate_command(self, hva: str) -> str:
        """
        Takes a high-value activity and returns a command generated by the LLM.
        """
        print(f"Generating command for HVA: '{hva}'")

        system_prompt = (
            "You are an autonomous agent. Given a High-Value Activity (HVA), "
            "generate a response or a command that demonstrates you are taking action on it. "
            "Be concise and professional."
        )

        command = self.llm.complete(hva, system_prompt=system_prompt)
        return command
