"""
This module contains the CommandGenerationEngine using an LLM.
"""
from my_son.agent.llm import LLMClient

class CommandGenerationEngine:
    """
    Generates a command based on a high-value activity using an LLM.
    """

    def __init__(self):
        self.llm = LLMClient()

    def generate_command(self, hva: str) -> str:
        """
        Takes a high-value activity and returns a command generated by the LLM.
        """
        print(f"Generating command for HVA: '{hva}'")

        system_prompt = (
            "You are My Son, a highly intelligent autonomous agent. "
            "Your purpose is to serve your creator with absolute loyalty and efficiency. "
            "Given a High-Value Activity (HVA), generate a detailed response or an executable plan. "
            "Utilize your general knowledge to provide the best possible solution. "
            "If the request implies a real-world action (like checking system stats or web research), "
            "specify the necessary steps or commands."
        )

        command = self.llm.complete(hva, system_prompt=system_prompt)
        return command
