"""
This module contains the ReflectionModule class using an LLM.
"""

import json
import re
from my_son.agent.llm import LLMClient

class ReflectionModule:
    """
    Reflects on the agent's performance and generates a self-correction plan using an LLM.
    """

    def __init__(self, log_file="performance.jsonl"):
        self.log_file = log_file
        self.llm = LLMClient()
        # Ensure log file exists
        try:
            with open(self.log_file, 'a'):
                pass
        except IOError:
            pass

    def run_reflection_cycle(self):
        """
        Reads the performance logs and generates a self-correction plan.
        """
        logs = []
        try:
            with open(self.log_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line:
                        logs.append(json.loads(line))
        except FileNotFoundError:
            return

        if not logs:
            return

        print("--- Running Reflection Cycle ---")

        # Analyze the last few logs (e.g., last 5) to avoid huge context
        recent_logs = logs[-5:]
        plan = self._generate_self_correction_plan(recent_logs)
        print("Reflection cycle complete.")
        return plan

    def _generate_self_correction_plan(self, logs):
        """
        Analyzes logs and generates a self-correction plan using the LLM.
        """
        prompt = f"Here are the recent performance logs of the agent:\n{json.dumps(logs, indent=2)}\n\n" \
                 "Identify the biggest bottleneck or area for improvement based on latency and response content. " \
                 "Generate a concrete Self-Correction Plan. " \
                 "Format the output as a JSON object with keys: 'issue', 'plan', 'suggested_fix'."

        system_prompt = "You are a senior software architect responsible for optimizing an autonomous agent."

        response = self.llm.complete(prompt, system_prompt=system_prompt)

        # Sanitize response
        response_clean = response.strip()
        if response_clean.startswith("```"):
            response_clean = re.sub(r"^```[a-z]*\n", "", response_clean)
            response_clean = re.sub(r"\n```$", "", response_clean)

        print(f"Self-Correction Plan generated by LLM:\n{response_clean}")
        return response_clean
