import os
import requests
import json
import logging
from my_son.brain.memory import Memory
from my_son.sync.swarm import SwarmManager

class LLMConnectionError(Exception):
    pass

class LLMClient:
    """
    A unified client handling Local Sovereignty (Ollama) as default, with fallbacks.
    Supports Swarm delegation and Multi-modal Vision.
    """

    def __init__(self, api_key=None, model="llama3", api_url="http://localhost:11434/api/generate"):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model # Default to local model name
        self.api_url = api_url # Default to Ollama
        self.logger = logging.getLogger(__name__)

        self.memory = Memory()
        self.swarm = SwarmManager()

        self.mode = "local"
        if self.api_key and "openai.com" in self.api_url:
            self.mode = "remote"

    def chat_complete(self, messages, max_tokens=1000, images=None):
        """
        Chat completion using /api/chat (Messages API).
        messages: List of {"role": "...", "content": "..."}
        """
        model_to_use = self.model
        if images and "llama" in self.model:
            model_to_use = "llava"

        # Construct endpoint URL (replace /api/generate with /api/chat)
        chat_url = self.api_url.replace("/api/generate", "/api/chat")

        data = {
            "model": model_to_use,
            "messages": messages,
            "stream": False,
            "options": {
                "num_predict": max_tokens,
                "temperature": 0.7
            }
        }

        # Note: Ollama /api/chat handles images inside the message object,
        # but for simplicity we assume the LAST message has the image if provided separately.
        if images:
            # Attach images to the last user message
            if messages and messages[-1]['role'] == 'user':
                messages[-1]['images'] = images

        try:
            response = requests.post(chat_url, json=data, timeout=60)
            response.raise_for_status()
            result = response.json().get('message', {}).get('content', '').strip()
            return result
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 404:
                 return f"[Error] Model '{model_to_use}' not found. Please run 'ollama pull {model_to_use}'."
            return f"[Error] HTTP Error: {e}"
        except Exception as e:
            self.logger.error(f"Chat LLM failed: {e}")
            return f"[Error] Brain offline: {e}"

    def complete(self, prompt, system_prompt="You are a helpful assistant.", max_tokens=1000, use_swarm=False, images=None):
        """
        Legacy completion using the local Sovereign Brain or the Swarm.
        Supports images (base64 encoded strings list).
        """
        # 1. Enhance Prompt with Long-Term Memory
        context = self.memory.retrieve_context(prompt)
        if context:
            memory_block = "\nRELEVANT MEMORIES:\n" + "\n".join([f"- {m}" for m in context]) + "\n"
            system_prompt += memory_block

        # 2. Store the new prompt in memory
        self.memory.save_context(prompt, "") # Store query part

        # 3. Execution (Swarm vs Local)
        # Note: Swarm delegation currently doesn't support images in our simplified protocol.
        # If images present, force local (or update swarm protocol later).
        result = None
        if use_swarm and not images:
            print("LLMClient: Attempting to delegate to Swarm...")
            result = self.swarm.delegate_task(prompt, system_prompt)
            if result:
                print("LLMClient: Generated by Swarm.")
            else:
                print("LLMClient: Swarm unavailable or failed. Falling back to local.")

        if not result:
            result = self._complete_local(prompt, system_prompt, max_tokens, images)
            print("LLMClient: Generated Locally.")

        # 4. Store response
        self.memory.save_context("", result) # Store response part

        return result

    def _complete_local(self, prompt, system_prompt, max_tokens, images=None):
        """
        Uses Requests to hit Ollama (Local).
        """
        # If images are present, we might need to switch model to 'llava' or compatible
        model_to_use = self.model
        if images:
            # Simple heuristic: If default is llama3, switch to llava for vision
            if "llama" in self.model:
                model_to_use = "llava"

        # Ollama /api/generate format
        data = {
            "model": model_to_use,
            "prompt": f"{system_prompt}\nUser: {prompt}\nAssistant:",
            "stream": False,
            "options": {
                "num_predict": max_tokens,
                "temperature": 0.7
            }
        }

        if images:
            data["images"] = images # List of base64 strings

        try:
            response = requests.post(self.api_url, json=data, timeout=60)
            response.raise_for_status()
            result = response.json().get('response', '').strip()
            return result
        except requests.exceptions.ConnectionError:
             self.logger.error("Local LLM Connection Refused. Is Ollama running?")
             raise LLMConnectionError("Could not connect to Ollama. Brain is offline.")
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 404:
                return f"[Error] Model '{model_to_use}' not found. Please run 'ollama pull {model_to_use}' in your terminal."
            return f"[Error] HTTP Error from Brain: {e}"
        except Exception as e:
            self.logger.error(f"Local LLM failed: {e}")
            # For chat, return string. For code/others, raise.
            # We'll return the error string but log it heavily.
            return f"[Error] My brain is offline. Please ensure Ollama is running with model '{model_to_use}'. ({e})"
